require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
